origLibPaths <- .libPaths()
if (tryCatch(packageVersion("crayon"), error = function(e) FALSE))
  withr::local_package("crayon", .local_envir = teardown_env())
if (tryCatch(packageVersion("waldo"), error = function(e) FALSE))
  withr::local_package("waldo", .local_envir = teardown_env())
if (tryCatch(packageVersion("rematch2"), error = function(e) FALSE))
  withr::local_package("rematch2", .local_envir = teardown_env())
if (tryCatch(packageVersion("diffobj"), error = function(e) FALSE))
  withr::local_package("diffobj", .local_envir = teardown_env())
if (tryCatch(packageVersion("terra"), error = function(e) FALSE))
  requireNamespace("terra", quietly = TRUE)
