origLibPaths <- .libPaths()
withr::local_package("crayon", .local_envir = teardown_env())
withr::local_package("waldo", .local_envir = teardown_env())
withr::local_package("rematch2", .local_envir = teardown_env())
withr::local_package("diffobj", .local_envir = teardown_env())
requireNamespace("terra", quietly = TRUE)
