# withr::local_options(list(repos = c(CRAN = "https://cloud.r-project.org")),
#                      .local_envir = teardown_env())
#
# # origLibPaths <- .libPaths()
# withr::local_libpaths(Require::tempdir2(.rndstr(1)))
# # withr::defer(.libPaths(origLibPaths), .local_envir = teardown_env())
# # withr::defer(.teardownProject(out$paths, origLibPaths))
#
# browser()
# tmpdir <- Require::tempdir2(sub = .rndstr(1))
# origWD <- getwd()
# setwd(tmpdir)
# withr::defer(setwd(origWD))
# withr::local_libpaths(Require::tempdir2(.rndstr(1)))
# withr::local_dir(Require::tempdir2(.rndstr(1)))
# browser()
#
#
# # withr::local_options(Require.RPackageCache = RequirePkgCacheDir(), .local_envir = teardown_env())
origLibPaths <- .libPaths()
if (tryCatch(packageVersion("crayon") > "0", error = function(e) FALSE))
  withr::local_package("crayon", .local_envir = teardown_env())
if (tryCatch(packageVersion("waldo") > "0", error = function(e) FALSE))
  withr::local_package("waldo", .local_envir = teardown_env())
if (tryCatch(packageVersion("rematch2") > "0", error = function(e) FALSE))
  withr::local_package("rematch2", .local_envir = teardown_env())
if (tryCatch(packageVersion("diffobj") > "0", error = function(e) FALSE))
  withr::local_package("diffobj", .local_envir = teardown_env())
if (tryCatch(packageVersion("terra") > "0", error = function(e) FALSE))
  requireNamespace("terra", quietly = TRUE)
